---
engines:
  bundler-audit:
    enabled: false
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.rb"
exclude_paths:
- spec/**/*
- test/**/*
- vendor/**/*
- bin/**/*
- .codeclimate.yml
