language: ruby
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
env:
 - RAILS_ENV=test RACK_ENV=test
notifications:
  email: false
