language: ruby
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.3
  - 2.2.4
  - 2.3.0
  - ruby-head
env:
 - RAILS_ENV=test RACK_ENV=test
notifications:
  email: false
