language: ruby
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
rvm:
  - 2.2.2
  - 2.2.5
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.4.0
env:
 - RAILS_ENV=test RACK_ENV=test
notifications:
  email: false
